[package]
name = "taiko_alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.6.0"
jzon = "0.12.5"
rodio = "0.17.3"
